version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Loging into Docker Hub
      - echo "$DOCKERHUB_TOKEN" | docker login --username $DOCKERHUB_USER --password-stdin

    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - docker-compose run --rm app sh -c "python manage.py"
      - docker-compose run --rm app sh -c "flake8"
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x9u5b6u1
      - docker build -t recipe-api .
      - docker tag recipe-api:latest public.ecr.aws/x9u5b6u1/recipe-api:latest
      - docker push public.ecr.aws/x9u5b6u1/recipe-api:latest
      - docker tag recipe-api:latest public.ecr.aws/x9u5b6u1/recipe-api:1.0
      - docker push public.ecr.aws/x9u5b6u1/recipe-api:1.0
